[package]
name = "ownership"
version = "0.1.0"
authors = ["Jesse A. Tov <jesse.tov@gmail.com>"]
edition = "2018"

[dependencies]
quickcheck = { version = "0.8", optional = true }

[dev-dependencies]
quickcheck = "0.8"
